return {
	directory = {
		home = { glyph = "" },
		nvim = { glyph = "", hl = "MiniIconsAzure" },
		snippets = { glyph = "󰩫", hl = "MiniIconsYellow" },

		-- Custom
		fish = { glyph = "", hl = "MiniIconsOrange" },
		hypr = { glyph = "", hl = "MiniIconsCyan" },
		zsh = { glyph = "", hl = "MiniIconsAzure" },
		nushell = { glyph = "", hl = "MiniIconsGreen" },
		powershell = { glyph = "󰨊", hl = "MiniIconsAzure" },
		sway = { glyph = "", hl = "MiniIconsAzure" },
		kitty = { glyph = "󰄛", hl = "MiniIconsOrange" },
		wezterm = { glyph = "", hl = "MiniIconsPurple" },
		["warp-terminal"] = { glyph = "", hl = "MiniIconsCyan" },
		mpv = { glyph = "󰃽", hl = "MiniIconsPurple" },
		vim = { glyph = "", hl = "MiniIconsGreen" },
		readonly = { glyph = "󰉐", hl = "MiniIconsYellow" },
		videos = { glyph = "󰃽", hl = "MiniIconsOrange" },
	},
	file = {
		[".bashrc"] = { glyph = "󱆃" },
		[".zshrc"] = { glyph = "" },

		-- Custom
		["lazy.lua"] = { glyph = "󰒲", hl = "MiniIconsAzure" },
		["config"] = { glyph = "", "MiniIconsGrey" },
		[".gitignore"] = { glyph = "󰊢", hl = "MiniIconsOrange" },
		[".vimrc"] = { glyph = "", hl = "MiniIconsGreen" },
		["config.fish"] = { glyph = "", hl = "MiniIconsOrange" },
		["hyprland.conf"] = { glyph = "", hl = "MiniIconsCyan" },
		[".env"] = { glyph = "", hl = "MiniIconsGrey" },
	},
	filetype = {
		-- Custom
		kde = { glyph = "", "MiniIconsPurple" },
		backup = { glyph = "󰁯", "MiniIconsGrey" },
	},
	lsp = {
		array = { glyph = "󰅪" },
		color = { glyph = "" },
		constant = { glyph = "󰏿" },
		constructor = { glyph = "" },
		enum = { glyph = "" },
		event = { glyph = "󱐋" },
		file = { glyph = "" },
		folder = { glyph = "󰉋" },
		["function"] = { glyph = "󰡱" },
		interface = { glyph = "" },
		key = { glyph = "󰌋" },
		method = { glyph = "󰆧" },
		module = { glyph = "" },
		namespace = { glyph = "󰅩" },
		object = { glyph = "󰅩" },
		snippet = { glyph = "󰩫" },
		string = { glyph = "󰉾" },
		text = { glyph = "" },
		typeparameter = { glyph = "󰆩" },
		value = { glyph = "󰎠" },
		variable = { glyph = "" },

		-- Custom
		breakstatement = { glyph = "󰙦", hl = "MiniIconsGreen" },
		["break"] = { glyph = "󰙦", hl = "MiniIconsAzure" },
		call = { glyph = "󰃷", hl = "MiniIconsGrey" },
		calc = { glyph = "󰃬", hl = "MiniIconsOrange" },
		casestatement = { glyph = "󱃙", hl = "MiniIconsPurple" },
		codeium = { glyph = "", hl = "MiniIconsGreen" },
		continuestatement = { glyph = "→", hl = "MiniIconsAzure" },
		copilot = { glyph = "", hl = "MiniIconsGreen" },
		declaration = { glyph = "󰙠", hl = "MiniIconsYellow" },
		delete = { glyph = "󰩺", hl = "MiniIconsRed" },
		dostatement = { glyph = "󰑖", hl = "MiniIconsPurple" },
		forstatement = { glyph = "󰑖", hl = "MiniIconsPurple" },
		h1marker = { glyph = "󰉫", hl = "MiniIconsBlue" }, -- Used by markdown treesitter parser
		h2marker = { glyph = "󰉬", hl = "MiniIconsBlue" },
		h3marker = { glyph = "󰉭", hl = "MiniIconsBlue" },
		h4marker = { glyph = "󰉮", hl = "MiniIconsBlue" },
		h5marker = { glyph = "󰉯", hl = "MiniIconsBlue" },
		h6marker = { glyph = "󰉰", hl = "MiniIconsBlue" },
		identifier = { glyph = "󰀫", hl = "MiniIconsCyan" },
		ifstatement = { glyph = "󰇉", hl = "MiniIconsPurple" },
		list = { glyph = "󰅪", hl = "MiniIconsAzure" },
		log = { glyph = "", hl = "MiniIconsGrey" },
		lsp = { glyph = "", hl = "MiniIconsYellow" },
		macro = { glyph = "󰁌", hl = "MiniIconsRed" },
		markdownh1 = { glyph = "󰉫", hl = "MiniIconsBlue" }, -- Used by builtin markdown source
		markdownh2 = { glyph = "󰉬", hl = "MiniIconsBlue" },
		markdownh3 = { glyph = "󰉭", hl = "MiniIconsBlue" },
		markdownh4 = { glyph = "󰉮", hl = "MiniIconsBlue" },
		markdownh5 = { glyph = "󰉯", hl = "MiniIconsBlue" },
		markdownh6 = { glyph = "󰉰", hl = "MiniIconsBlue" },
		regex = { glyph = "", hl = "MiniIconsCyan" },
		["repeat"] = { glyph = "󰑖", hl = "MiniIconsOrange" },
		scope = { glyph = "󰅩", hl = "MiniIconsGreen" },
		specifier = { glyph = "󰦪", hl = "MiniIconsOrange" },
		statement = { glyph = "󰅩", hl = "MiniIconsYellow" },
		switchstatement = { glyph = "󰺟", hl = "MiniIconsPurple" },
		treesitter = { glyph = "", hl = "MiniIconsGreen" },
		type = { glyph = "", hl = "MiniIconsOrange" },
		whilestatement = { glyph = "󰑖", hl = "MiniIconsPurple" },

		question = { glyph = "", hl = "MiniIconsPurple" },
		hint = { glyph = "", hl = "MiniIconsGreen" },
		info = { glyph = "", hl = "MiniIconsCyan" },
		warning = { glyph = "", hl = "MiniIconsYellow" },
		error = { glyph = "", hl = "MiniIconsRed" },
		bug = { glyph = "", hl = "MiniIconsRed" },
	},
	os = {
		android = { glyph = "" },
		centos = { glyph = "" },
		linux = { glyph = "" },
		nixos = { glyph = "" },
		raspberry_pi = { glyph = "" },
		redhat = { glyph = "󱄛" },
		ubuntu = { glyph = "" },
		windows = { glyph = "" },

		-- Custom
		alpine = { glyph = "", hl = "MiniIconsCyan" },
		amazon = { glyph = "", hl = "MiniIconsYellow" },
		elementary = { glyph = "", hl = "MiniIconsAzure" },
		endeavouros = { glyph = "", hl = "MiniIconsPurple" },
		garuda = { glyph = "", hl = "MiniIconsOrange" },
		illumos = { glyph = "", hl = "MiniIconsOrange" },
		midnightbsd = { glyph = "", hl = "MiniIconsGrey" },
		openbsd = { glyph = "", hl = "MiniIconsOrange" },
		popos = { glyph = "", hl = "MiniIconsCyan" },
		slackware = { glyph = "", hl = "MiniIconsAzure" },
		solus = { glyph = "", hl = "MiniIconsAzure" },
		suse = { glyph = "", hl = "MiniIconsGreen" },
		windowsxp = { glyph = "󰨡", hl = "MiniIconsBlue" },
		zorin = { glyph = "", hl = "MiniIconsCyan" },
	},

	-- Custom
	folder = {
		files = { glyph = " " },
		folder = { glyph = " " },
		folderempty = { glyph = " " },
		filelocked = { glyph = "󰈡 " },
		folderlocked = { glyph = "󰉐 " },
		openfolder = { glyph = " " },
		openfolderempty = { glyph = " " },
		symlink = { glyph = " " },
		symlinkfolder = { glyph = " " },
		import = { glyph = " " },
	},
	git = {
		add = { glyph = "" },
		branch_curve = { glyph = "" },
		branch_sharp = { glyph = "" },
		branch_fill = { glyph = "" },
		compare = { glyph = "" },
		diff = { glyph = "" },
		ignore = { glyph = "◌" },
		merge = { glyph = "" },
		mod = { glyph = "" },
		octoface = { glyph = "" },
		remove = { glyph = "" },
		rename = { glyph = "➜" },
		repo = { glyph = "" },
		tag = { glyph = "" },
		untrack = { glyph = "★" },
	},
	extra = {
		pacman = { glyph = "󰮯" },
		ghost = { glyph = "󰊠" },
		hash = { glyph = "" },
		yinyang = { glyph = "" },
		biohazard = { glyph = "󰂧" },
		enabled = { glyph = "" },
		font = { glyph = "" },
		laptop = { glyph = "" },
		cpu = { glyph = "󰍛" },
		monitor = { glyph = "󰍹" },
		ram = { glyph = "" },
		clock = { glyph = "󰅐" },
		image = { glyph = "" },
	},
	ui = {
		arrow = { glyph = "➜" },
		arrowclosed = { glyph = "►" },
		arrowleft = { glyph = "" },
		arrowopen = { glyph = "▼" },
		arrowright = { glyph = "" },
		arrowdownandright = { glyph = "󱞩" },
		arrowdownandleft = { glyph = "󱞥" },
		arrowrightandup = { glyph = "󱞿" },
		arrowleftandup = { glyph = "󱞽" },
		arrowrightanddown = { glyph = "󱞣" },
		arrowleftanddown = { glyph = "󱞡" },
		bluetooth = { glyph = "" },
		bookmark = { glyph = "" },
		bottom = { glyph = "" },
		bug = { glyph = "" },
		calendar = { glyph = "" },
		camera = { glyph = "" },
		checkCircle = { glyph = "●" },
		check = { glyph = "" },
		chevronRight = { glyph = "" },
		circle = { glyph = "" },
		circleSmall = { glyph = "●" },
		circleSmallEmpty = { glyph = "○" },
		clipboard = { glyph = "" },
		close = { glyph = "" },
		code = { glyph = "" },
		collection = { glyph = "" },
		color = { glyph = "" },
		command = { glyph = "" },
		comment = { glyph = "" },
		corner = { glyph = "" },
		dashboard = { glyph = "" },
		database = { glyph = "" },
		download = { glyph = "" },
		edge = { glyph = "│" },
		electric = { glyph = "󱐋" },
		fire = { glyph = "" },
		firefox = { glyph = "" },
		game = { glyph = "" },
		gear = { glyph = "" },
		github = { glyph = "" },
		heart = { glyph = "" },
		history = { glyph = "" },
		home = { glyph = "" },
		incoming = { glyph = "" },
		item = { glyph = "" },
		keyboard = { glyph = " " },
		list = { glyph = "" },
		lock = { glyph = "" },
		minus = { glyph = "‒" },
		music = { glyph = "󰝚" },
		neovim = { glyph = "" },
		newfile = { glyph = "" },
		none = { glyph = "" },
		note = { glyph = "" },
		oldfiles = { glyph = "" },
		outgoing = { glyph = "" },
		package = { glyph = "" },
		paint = { glyph = "" },
		pause = { glyph = "" },
		pencil = { glyph = "" },
		person = { glyph = "" },
		pin = { glyph = "車" },
		play = { glyph = "" },
		plug = { glyph = "" },
		plus = { glyph = "" },
		power = { glyph = "" },
		powerlinerightround = { glyph = "" },
		powerlinerighttriangle = { glyph = "" },
		powerlineleftround = { glyph = "" },
		powerlinelefttriangle = { glyph = "" },
		project = { glyph = "" },
		question = { glyph = "" },
		reload = { glyph = "" },
		rocket = { glyph = "" },
		search = { glyph = "" },
		signin = { glyph = "" },
		signout = { glyph = "" },
		sleep = { glyph = "󰒲" },
		star = { glyph = "󰓎" },
		table = { glyph = "" },
		telescope = { glyph = "󰭎" },
		inverttelescope = { glyph = "" },
		terminal = { glyph = "" },
		test = { glyph = "" },
		time = { glyph = "" },
		tick = { glyph = "" },
		top = { glyph = "" },
		trash = { glyph = "" },
		triplegear = { glyph = "" },
		uncheck = { glyph = "○" },
		["vim"] = { glyph = "" },
		wifi = { glyph = "" },
		windows = { glyph = "" },
	},
}
