name: Bug report
description: "Report a bug/issue here."
title: "bug: "
labels: [bug]
assignees: [daUnknownCoder]

body:
  - type: markdown
    attributes:
      value: |
        **Before reporting any bug/issue, please make sure to search among [existing issues](https://github.com/daUnknownCoder/NeutronVim/issues).**
  - type: checkboxes
    attributes:
      label: Did you browse among the existing issues?
      description: Make sure to check all among the below options before reporting a bug/issue.
      options:
        - label: I have searched the existing issues of NeutronVim.
          required: true
        - label: I have searched the existing issues of plugins related to this issue.
          required: true
  - type: input
    attributes:
      label: "Neovim version"
      placeholder: "e.g. 0.8.0 commit db1b0ee3b30f"
    validations:
      required: true
  - type: input
    attributes:
      label: "Operating system/version"
    placeholder: "e.g. macOS 11.5"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce the bug."
    placeholder: |
      1.
      2.
      3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "Describe the expected behavior."
    validations:
      required: true
